name: Add label

on:
  pull_request:
    types: [assigned]

jobs:
  add_label:
    runs-on: ubuntu-latest
    environment: test-1
    permissions:
      contents: read
      issues: read
      pull-requests: write
    if: contains(github.event.pull_request.assigned.*.login, fromJson(vars.MANAGERS))
    steps:
      - name: Add label
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['needs-review']
            })